apiVersion: v1
kind: Service
metadata:
  name: redis-flask-app-service
  labels:
    app: redis-flask-app
spec:
  type: LoadBalancer
  selector:
    app: redis-flask-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
