apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: redis-app
spec:
  type: LoadBalancer
  selector:
    app: redis-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
