# Updated task parameters per user request
rg_name           = "cmaz-3o15j4kj-mod4-rg"
location          = "eastus"
vnet_name         = "cmaz-3o15j4kj-mod4-vnet"
subnet_name       = "frontend"
nic_name          = "cmaz-3o15j4kj-mod4-nic"
nsg_name          = "cmaz-3o15j4kj-mod4-nsg"
nsg_rule_http     = "AllowHTTP"
nsg_rule_ssh      = "AllowSSH"
public_ip         = "cmaz-3o15j4kj-mod4-pip"
domain_name_label = "cmaz-3o15j4kj-mod4-nginx"
vm_name           = "cmaz-3o15j4kj-mod4-vm"
vm_SKU            = "Standard_B2s_v2"
admin_username    = "azureuser"
student_email     = "nurgazy_sydykov@epam.com"
ip_configuration_name = "internal"

# Image SKU/version
vm_os_publisher = "Canonical"
vm_os_offer     = "ubuntu-24_04-lts"
vm_os_sku       = "ubuntu-pro"
vm_os_version   = "latest"
